.dind:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

.base-rules:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - $RULES_CHANGES_PATH
    - when: manual
      allow_failure: true

.backend:
  extends: .base-rules
  variables:
    RULES_CHANGES_PATH: "backend/**/*"

.frontend:
  extends: .base-rules
  variables:
    RULES_CHANGES_PATH: "frontend/**/*"

build-backend:
  stage: build
  extends:
    - .backend
    - .dind
  script:
    - cd backend/
    - docker build --pull -t "$CI_REGISTRY_IMAGE/backend" .
    - docker push "$CI_REGISTRY_IMAGE/backend"

build-frontend:
  stage: build
  extends: .frontend
  image: node:lts
  script:
    - cd frontend/
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist/

deploy-frontend:
  stage: deploy
  extends: .frontend
  image: node:lts
  needs:
    - build-frontend
  script:
    - cd frontend/
    - npm install -g wrangler
    - npx wrangler pages deploy dist --project-name=$CLOUDFLARE_PROJECT_NAME --branch=main
