image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

.base-rules:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - $RULES_CHANGES_PATH
    - when: manual
      allow_failure: true

.backend:
  extends: .base-rules
  variables:
    RULES_CHANGES_PATH: "backend/**/*"

build-backend:
  stage: build
  extends: .backend
  script:
    - cd backend/
    - docker build --pull -t "$CI_REGISTRY_IMAGE/backend" .
    - docker push "$CI_REGISTRY_IMAGE/backend"
