version: "3"

services:
  backend:
    image: containers.0b101010.codes/playground/smm-zerop-backend:latest
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./config:/app/config
