name: backend

on:
  workflow_dispatch:
  push:
    paths:
      - backend/**
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: code.schub.bar
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: backend/
          push: true
          tags: |
            code.schub.bar/${{ github.repository }}/backend:latest
