name: frontend

on:
  workflow_dispatch:
  push:
    paths:
      - frontend/**
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: https://code.schub.bar/actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y rsync
      - uses: https://code.schub.bar/actions/setup-node@v4
        with:
          node-version: 20
      - name: build and deploy
        working-directory: frontend/
        run: |
          echo "Building..."
          npm i
          npm run build

          echo "Getting SSH key..."
          curl -so /tmp/ssh-key -H  "Authorization: Bearer ${{ secrets.SECRET_TOKEN }}" "${{ vars.SECRET_URL }}"
          chmod 600 /tmp/ssh-key

          echo "Syncing files..."
          rsync -rz --delete -e "${{ vars.RSYNC_CONNECT_PROG }}" ./dist/ "${{ vars.RSYNC_TARGET }}"
