name: release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  docker-release:
    runs-on: ubuntu-latest
    steps:
      - uses: https://code.schub.bar/actions/checkout@v4
      - uses: https://code.schub.bar/actions/docker-login-action@v3
        with:
          registry: code.schub.bar
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_TOKEN }}
      - uses: https://code.schub.bar/actions/docker-metadata-action@v5
        id: docker-meta
        with:
          images: |
            code.schub.bar/${{ github.repository }}
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - uses: https://code.schub.bar/actions/docker-build-push-action@v6
        id: docker_build
        with:
          context: .
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
      - id: artifact_packaging
        name: packaging artifact
        run: |
          mkdir out/ && cd out/
          container=$(docker create ${{ steps.docker_build.outputs.imageid }})
          docker cp $container:/app .
          echo "version=$(./app/web --version | awk -F ' ' '{print $2}')" >> $GITHUB_OUTPUT
          cd app/ && tar -cvf ../smm-zerop.tar .
      - uses: https://code.schub.bar/actions/forgejo-upload-artifact@v4
        with:
          name: smm-zerop-${{ steps.artifact_packaging.outputs.version }}-linux-amd64.tar.zip
          path: ./out/smm-zerop.tar
