name: test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: https://code.schub.bar/actions/checkout@v4
      - uses: https://code.schub.bar/binarygale-gha/rust-short-lived-cache@v2
      - uses: https://code.schub.bar/binarygale-gha/rust-toolchain@v1
      - run: cargo build --all-targets --all-features --profile test

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: https://code.schub.bar/actions/checkout@v4
      - uses: https://code.schub.bar/binarygale-gha/rust-short-lived-cache@v2
      - uses: https://code.schub.bar/binarygale-gha/rust-toolchain@v1
      - run: cargo test --all-targets --all-features -- --color=always

  clippy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: https://code.schub.bar/actions/checkout@v4
      - uses: https://code.schub.bar/binarygale-gha/rust-short-lived-cache@v2
      - uses: https://code.schub.bar/binarygale-gha/rust-toolchain@v1
      - run: cargo clippy --all-targets --all-features -- -D warnings

  rustfmt:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: https://code.schub.bar/actions/checkout@v4
      - uses: https://code.schub.bar/binarygale-gha/rust-short-lived-cache@v2
      - uses: https://code.schub.bar/binarygale-gha/rust-toolchain@v1
      - run: cargo fmt --all -- --check
