name: backend

on:
  workflow_dispatch:
  push:
    paths:
      - backend/**
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: backend/
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/backend:latest
